# Generated by Django 2.2.6 on 2020-08-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('С жестким крылом', 'С жестким крылом'), ('С гибким крылом', 'С гибким крылом'), ('С вращающимся крылом', 'С вращающимся крылом'), ('С машущим крылом', 'С машущим крылом'), ('Аэростатические', 'Аэростатические')], max_length=64, verbose_name='Тип БПЛА')),
                ('classification', models.CharField(choices=[('Микро-мини', 'Микро-мини'), ('Лёгкий малого радиуса', 'Лёгкий малого радиуса'), ('Лёгкий среднего радиуса', 'Лёгкий среднего радиуса'), ('Средний', 'Средний'), ('Средне-тяжелый', 'Средне-тяжелый'), ('Тяжелый среднего радиуса', 'Тяжелый среднего радиуса'), ('Тяжелый с продолжительным полетом', 'Тяжелый с продолжительным полетом'), ('Боевой', 'Боевой')], max_length=64, verbose_name='Класс БПЛА')),
                ('weight', models.FloatField(verbose_name='Вес БПЛА')),
                ('photo', models.ImageField(upload_to='BPLA_images')),
                ('verification', models.CharField(choices=[('На проверке', 'На проверке'), ('Верифирован', 'Верифирован'), ('Отказ', 'Отказ')], max_length=64, verbose_name='Статус верификации')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'БПЛА',
                'verbose_name_plural': 'БПЛА',
            },
        ),
    ]
