# Generated by Django 2.2.6 on 2020-08-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBAS', '0002_auto_20200830_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='end_flight',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='start_flight',
            field=models.DateTimeField(null=True),
        ),
    ]
