# Generated by Django 2.2.6 on 2020-08-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBAS', '0003_auto_20200830_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='end_flight',
            field=models.DateTimeField(null=True),
        ),
    ]
