# Generated by Django 2.2.6 on 2020-09-14 13:26

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flightBAS', '0004_auto_20200831_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='condition_weather',
            field=models.CharField(default='da', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='speed_wind',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='temperature_weather',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='polygon',
            field=jsonfield.fields.JSONField(),
        ),
    ]
