# Generated by Django 2.2.6 on 2020-09-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBAS', '0005_auto_20200914_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='dew_point',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='gusting',
            field=models.FloatField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='heading',
            field=models.FloatField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='visibility',
            field=models.FloatField(default=17),
            preserve_default=False,
        ),
    ]
