# Generated by Django 2.2.6 on 2020-09-18 04:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flightBAS', '0007_coorsflight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoorsFlight',
            new_name='CoordsFlight',
        ),
    ]
